// <auto-generated />
namespace Guestbook.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _201509071055 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201509071055));
        
        string IMigrationMetadata.Id
        {
            get { return "201507090756059_2015-09-07-10-55"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
