// <auto-generated />
namespace Guestbook.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _0044 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0044));
        
        string IMigrationMetadata.Id
        {
            get { return "201507092144205_00-44"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
