// <auto-generated />
namespace Guestbook.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _201507111029 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201507111029));
        
        string IMigrationMetadata.Id
        {
            get { return "201507110729497_2015-07-11-10-29"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
